kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: golang:1.12.4-alpine3.9
    commands:
      - export GO_VERSION=$(go version)
      - "go build -ldflags \"-X main.gitVersion=${DRONE_COMMIT_SHA:0:8} -X 'main.goVersion=$GO_VERSION'\" -o drone-oss-cache"
    environment:
      CGO_ENABLED: 0

  - name: docker
    image: plugins/docker
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: luischan/drone-oss-cache
      tags: latest
